imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@ODADneprMockServiceBundle/Resources/config/parameters.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    exception_controller:  odadnepr.exceptions:showAction

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

lexik_jwt_authentication:
    private_key_path: %jwt_private_key_path%
    public_key_path:  %jwt_public_key_path%
    pass_phrase:      %jwt_key_pass_phrase%
    token_ttl:        %jwt_token_ttl%

nelmio_api_doc:
    sandbox:
        accept_type: application/json
        body_format:
            default_format: json
        authentication:
            name: Authorization
            delivery: header
            type: bearer

fos_rest:
    routing_loader:
        default_format: json
    view:
        view_response_listener: true
        # only relevant when using the JMS serializer for serialization
    format_listener:
        rules:
            # setting fallback_format to json means that instead of considering the next rule in case of a priority mismatch, json will be used
            - { path: '^/', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }


sensio_framework_extra:
    view:
        annotations: false

vich_uploader:
    db_driver: orm
    mappings:
        ticket_file:
            uri_prefix:         /files/ticket/
            upload_destination: %kernel.root_dir%/../web/files/ticket/

services:
    geo:
        class: ODADnepr\MockServiceBundle\Service\Geo
        arguments: [@doctrine.orm.default_entity_manager]
    odadnepr.exceptions:
        class: ODADnepr\MockServiceBundle\Controller\ExceptionController
        arguments: [@twig, %kernel.debug%]
        calls:
        - [ setContainer, [@service_container] ]

    app.tokens.action_listener:
        class: ODADnepr\MockServiceBundle\EventListener\TokenListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
