security:
    encoders:
        Symfony\Component\Security\Core\User\UserInterface: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
#        in_memory:
#            memory:
#                users:
#                    user:  { password: userpass, roles: [ 'ROLE_USER', 'ROLE_API' ] }
#                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN', 'ROLE_API' ] }
        oda_provider:
            id: oda.user_provider.email

    firewalls:
        login:
            pattern:  ^/rest/v1/user-auth
            stateless: true
            anonymous: true
            form_login:
                check_path:               /rest/v1/user-auth-check
                username_parameter: username
                password_parameter: password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
        free_api:
            pattern: ^/rest/v1/(address|generate|ticket\-categories)
            stateless: true
            anonymous: true

        api:
            pattern:   ^/rest
            stateless: true
            lexik_jwt: ~

    access_control:
        - { path: ^/rest/v1/(address|generate|ticket\-categories), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/rest,       roles: IS_AUTHENTICATED_FULLY }