# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\UserInterface: plaintext
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        oda_provider:
            id: oda.user_provider.email

    firewalls:
        login:
            pattern:  ^/rest/v1/user-auth
            stateless: true
            anonymous: true
            form_login:
                check_path:               /rest/v1/user-auth-check
                username_parameter: username
                password_parameter: password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        registration:
            pattern: ^/rest/v1/user-register
            anonymous: true
            stateless: true

        free_api:
            pattern: ^/rest/v1/(address-book|vocabulary|tickets)
            stateless: true
            anonymous: true

        api:
            pattern:   ^/rest
            stateless: true
            lexik_jwt: ~

    access_control:
        - { path: ^/rest/v1/(address-book|vocabulary|tickets), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/rest/v1/user-register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/rest,       roles: IS_AUTHENTICATED_FULLY }