<?php

namespace ODADnepr\MockServiceBundle\Entity;

use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpKernel\Exception\BadRequestHttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;


/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OdaEntityManager
{
    /* @var ObjectManager */
    protected $entityManager;

    /**
     * Constructor.
     *
     * @param ObjectManager $entityManager
     */
    public function __construct(ObjectManager $entityManager)
    {
        $this->entityManager = $entityManager;
    }

    public function setAddress(Address $address)
    {
        $repo = $this->entityManager->getRepository('ODADneprMockServiceBundle:Address');
        $id = $address->getId();
        if (!$id || !($address_entity = $repo->find($address->getId()))) {
            $district = $this->setDistrict($address->getDistrict());
            $city = $this->setCity($address->getCity());
            $street = $this->setStreet($address->getStreet());
            $house = $this->setHouse($address->getHouse());
            $address_entity = new Address();
            $address_entity->setStreet($street);
            $address_entity->setCity($city);
            $address_entity->setDistrict($district);
            $address_entity->setHouse($house);
            $address_entity->setFlat($address->getFlat());
            $this->entityManager->persist($address_entity);
            $this->entityManager->flush();
        }

        return $address_entity;
    }

    public function setDistrict(District $district_object)
    {
        $repo = $this->entityManager->getRepository('ODADneprMockServiceBundle:District');
        $district = $repo->find($district_object->getId());
        if (!$district) {
            throw new NotFoundHttpException('District with ID=' . $district_object->getId() . ' was not found');
        }

        return $district;
    }

    public function setCity(City $city_object)
    {
        $repo = $this->entityManager->getRepository('ODADneprMockServiceBundle:City');
        $city = $repo->find($city_object->getId());
        if (!$city) {
            throw new NotFoundHttpException('City with ID=' . $city->getId() . ' was not found');
        }

        return $city;
    }

    public function setStreet(Street $street_object)
    {
        $repo = $this->entityManager->getRepository('ODADneprMockServiceBundle:Street');
        $street = $repo->find($street_object->getId());

        if (!$street) {
            throw new NotFoundHttpException('Street with ID=' . $street->getId() . ' was not found');
        }

        return $street;
    }

    public function setHouse(House $house_object)
    {
        $repo = $this->entityManager->getRepository('ODADneprMockServiceBundle:House');
        $house = $repo->find($house_object->getId());
        if (!$house) {
            throw new NotFoundHttpException('House with ID=' . $house->getId() . ' was not found');
        }

        return $house;
    }

    public function setFacilities(Facilities $facilities) {
        $repo = $this->entityManager->getRepository('ODADneprMockServiceBundle:Facilities');
        $facilities = $repo->find($facilities->getId());
        if (!$facilities) {
            throw new NotFoundHttpException('Facilities with ID=' . $facilities->getId() . ' was not found');
        }

        return $facilities;
    }

    public function setSocialCondition(SocialCondition $socialCondition) {
        $repo = $this->entityManager->getRepository('ODADneprMockServiceBundle:SocialCondition');
        $socialCondition = $repo->find($socialCondition->getId());
        if (!$socialCondition) {
            throw new NotFoundHttpException('Social condition with ID=' . $socialCondition->getId() . ' was not found');
        }

        return $socialCondition;
    }

    public function getUser(User $user_object)
    {
        $repo = $this->entityManager->getRepository('ODADneprMockServiceBundle:User');

        $user = $repo->find($user_object->getId());
        if (!$user) {
            throw new NotFoundHttpException('Ticket category with ID=' . $user->getId() . ' was not found');
        }

        return $user;
    }

    public function getManager($manager_object)
    {
        if (is_null($manager_object)) {
            return null;
        }

        $repo = $this->entityManager->getRepository('ODADneprMockServiceBundle:Manager');

        if (!isset($manager_object->id) || !($manager = $repo->find($manager_object->id))) {
            $manager = new Manager();
            $manager->setName($manager_object->name);
            $this->entityManager->persist($manager);
            $this->entityManager->flush();
        }

        return $manager;
    }

    public function getCategory(TicketCategory $category_object)
    {
        $repo = $this->entityManager->getRepository('ODADneprMockServiceBundle:TicketCategory');

        $category = $repo->find($category_object->getId());
        if (!$category) {
            throw new NotFoundHttpException('Ticket category with ID=' . $category->getId() . ' was not found');
        }

        return $category;
    }

    public function getType(TicketType $type)
    {
        $repo = $this->entityManager->getRepository('ODADneprMockServiceBundle:TicketType');

        $type = $repo->find($type->getId());
        if (!$type) {
            throw new NotFoundHttpException('Ticket type with ID=' . $type->getId() . ' was not found');
        }

        return $type;
    }
}
